// <auto-generated />
using System;
using Alexandria.Crawler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alexandria.Crawler.Services.Migrations
{
    [DbContext(typeof(CrawlerDbContext))]
    partial class CrawlerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.CrawlSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedPages")
                        .HasColumnType("int");

                    b.Property<int>("MaxDepth")
                        .HasColumnType("int");

                    b.Property<int>("MaxPages")
                        .HasColumnType("int");

                    b.Property<string>("StartUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SuccessfulPages")
                        .HasColumnType("int");

                    b.Property<int>("TotalPagesCrawled")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("CrawlSessions");
                });

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.CrawledPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CrawlDepth")
                        .HasColumnType("int");

                    b.Property<Guid?>("CrawlSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CrawledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("CrawlSessionId");

                    b.HasIndex("CrawledAt");

                    b.HasIndex("Domain");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("CrawledPages");
                });

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.ExtractedImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("ExtractedImages");
                });

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.ExtractedLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnchorText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<Guid>("SourcePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("SourcePageId");

                    b.HasIndex("TargetUrl");

                    b.HasIndex("SourcePageId", "TargetUrl");

                    b.ToTable("ExtractedLinks");
                });

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.PageMetaData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetaKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MetaValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MetaKey");

                    b.HasIndex("PageId");

                    b.ToTable("PageMetaData");
                });

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.CrawledPage", b =>
                {
                    b.HasOne("Alexandria.Crawler.Data.Entities.CrawlSession", "CrawlSession")
                        .WithMany("CrawledPages")
                        .HasForeignKey("CrawlSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CrawlSession");
                });

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.ExtractedImage", b =>
                {
                    b.HasOne("Alexandria.Crawler.Data.Entities.CrawledPage", "Page")
                        .WithMany("ExtractedImages")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.ExtractedLink", b =>
                {
                    b.HasOne("Alexandria.Crawler.Data.Entities.CrawledPage", "SourcePage")
                        .WithMany("ExtractedLinks")
                        .HasForeignKey("SourcePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourcePage");
                });

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.PageMetaData", b =>
                {
                    b.HasOne("Alexandria.Crawler.Data.Entities.CrawledPage", "Page")
                        .WithMany("MetaData")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.CrawlSession", b =>
                {
                    b.Navigation("CrawledPages");
                });

            modelBuilder.Entity("Alexandria.Crawler.Data.Entities.CrawledPage", b =>
                {
                    b.Navigation("ExtractedImages");

                    b.Navigation("ExtractedLinks");

                    b.Navigation("MetaData");
                });
#pragma warning restore 612, 618
        }
    }
}
